### PR TITLE
fix #151 - add exception for FF for 201 202 204 205 codes

### LINKED ISSUE #151: Some more "no content" responses need fixed for Firefox
Related to #111 

Reported by @Mouvedia in https://github.com/naugtur/xhr/pull/121#discussion_r95722286

In Firefox, 201/202/205 responses need to be manually fixed to not return XMLDocuments in the same way as 204 responses.

Relevant code: https://github.com/naugtur/xhr/blob/b9ba803a2800a16e30c5e6f7a208eba8143eb5cd/index.js#L233

### PR DESCRIPTION
**Pull request by naugtur**
This is not ready to merge - see #151 for discussion.

To understand why, pull this branch and replace the 201 test with 200, then `npm run browser`, open in FireFox and watch it fail

### CODE REVIEW

**Comment by naugtur** [comment]
Ok, that's the fix. Will merge+release soon.

File: test/mock-server.js [hunk 1]
```diff
@@ -3,8 +3,8 @@ module.exports = function(req, res) {
     if (req.url === '/mock/200ok') {
         res.statusCode = 200
         res.end('')
-    } else if (req.url === '/mock/no-content') {
-        res.statusCode = 204
+    } else if (req.url.substr(0,16) === '/mock/no-content') {
+        res.statusCode = ~~(req.url.substring(17))
```
Comment (TehShrike) [inline test/mock-server.js]: As far as super-brief casting shortcuts go, I think `+(req.url.substring(17))` would be more commonly understood (though I do tend towards the explicit `parseInt(req.url.substring(17), 10)` myself)

Comment (naugtur) [inline test/mock-server.js]: Nice thing about `~~` compared with `parseInt` is that they return `0` and `NaN` respectively for invalid input. But this is a mockserver, so understandability seems more important than fault-tolerance. 

I merged this already, so fixing in master.
